SELECT
NVL(LISTAGG(''''||TBL_NM||'''', ','), ''' ''') AS TBLS
FROM STGOWN.DOPCO_SORVL_D
WHERE JOB_TYPE LIKE 'UC_'
AND UN_DB = 'CBS'
AND PRJ_PATH LIKE '%DOP'
;


DOP_CO_SORVL_L

BASE_DT CHAR
TBL_ENNM CHAR
VALDTN_CCNT  INTEGER EXTERNAL